=== justinliucs/haflow/src/main/resources/full.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.xml.util.haflow"
xmlns="http://www.xml.util.haflow"
elementFormDefault="qualified">

<xs:complexType name="erPropertiesType">
	<xs:sequence>	
		<xs:element name="jarPath" type="xs:string"/>
		<xs:element name="inputPath" type="xs:string"/>
		<xs:element name="outputPath" type="xs:string"/>
		<xs:element name="confPath" type="xs:string"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="positionType">
	<xs:sequence>	
		<xs:element name="x" type="xs:double"/>
		<xs:element name="y" type="xs:double"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="erModuleType">
	<xs:sequence>
		<xs:element name="id" type="xs:string"/>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="_type" type="xs:string"/>
		<xs:element name="mtype" type="xs:string"/>
		<xs:element name="erProperties" type="erPropertiesType"/>
		<xs:element name="position" type="positionType"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="flowType">
	<xs:sequence>
		<xs:element name="id" type="xs:string"/>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="type" type="xs:string"/>
		<xs:element name="parent" minOccurs="0" maxOccurs="1" type="xs:string"/>
		<xs:element name="tabid" type="xs:string"/>
		<xs:element name="erModule" minOccurs="0" maxOccurs="unbounded" type="erModuleType"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="project">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="identifier" type="xs:string"/>
			<xs:element name="label" type="xs:string"/>
			<xs:element name="items" maxOccurs="unbounded" type="flowType"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== justinliucs/haflow/src/main/resources/full.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<project  xmlns="http://www.xml.util.haflow"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.xml.util.haflow full.xsd">
    <identifier>id</identifier>
	<label>name</label>
    
    <items>
        <id>EntryFlow_id</id>
        <name>EntryFlow</name>
		<type>FLOW</type>        
		<tabid>tab_EntryFlow_id</tabid>
		<erModule>
			<id>pid1-entryFlow1-0</id>
			<name>ER</name>
			<_type>String</_type>
			<mtype>ER-MODULE</mtype>
			<erProperties>
				<jarPath>jar</jarPath>
				<inputPath>input</inputPath>
				<outputPath>output</outputPath>
				<confPath>conf</confPath>
			</erProperties>
			<position>
				<x>100</x>
				<y>200</y>
			</position>
		</erModule>

	</items>
    <items>
        <id>HiveFlow_id</id>
        <name>HiveFlow</name>
		<type>SUBFLOW</type>        		
		<tabid>tab_HiveFlow_id</tabid>
    </items>
	<items>
        <id>aa_id</id>
        <name>aa</name>
        <type>FLOW</type>
        <tabid>tab_aa_id</tabid>
    </items>
</project>
